version: "2"

services:

  influxdb:

    image: influxdb:latest

    network_mode: "host"
    restart: "unless-stopped"

    volumes:
      - type: bind
        source: /data2/influxdb2
        target: /var/lib/influxdb2


  grafana:

    image: grafana/grafana:latest
    network_mode: "host"
    restart: "unless-stopped"

    volumes:
      - type: bind
        source: /data2/grafana
        target: /var/lib/grafana

